# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r:
  - release
  - devel
  - oldrel
os:
  - linux
  - osx
matrix:
  exclude:
    - r: devel
      os: osx
latex: false
warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov(type = "all", line_exclusions = "R/shiny.R")'
